# yaml-language-server: $schema=https://deltares.github.io/veriflow/v0/config.schema.json
version: v0
general:
  verification_period:
    dimension: forecast_reference_time
    start: "2025-05-20T00:00:00Z"
    end: "2026-06-01T00:00:00Z"
  verification_pairs:
    - id: QR_GEPS
      observations_source_id: observed
      simulations_source_id: simulated_GEPS
      variable: discharge
    - id: QR_GEFS
      observations_source_id: observed
      simulations_source_id: simulated_GEFS
      variable: discharge
    - id: QR_IFS
      observations_source_id: observed
      simulations_source_id: simulated_IFS
      variable: discharge
  lead_times:
    unit: D
    values: [1, 2, 3, 4, 5, 6]
datasources:
  - import_adapter: fewswebservice
    source_id: observed
    data_type: observed_historical
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.obs
    module_instance_id: ImportWSC
    webservice_version: "2025.02"

  - import_adapter: fewswebservice
    source_id: simulated_GEPS
    data_type: simulated_forecast_ensemble
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.sim
    module_instance_id: ElbowRavenGEPSForecast
    ensemble_id: GEPS
    webservice_version: "2025.02"

  - import_adapter: fewswebservice
    source_id: simulated_GEFS
    data_type: simulated_forecast_ensemble
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.sim
    module_instance_id: ElbowRavenGEFSForecast
    ensemble_id: GEFS
    webservice_version: "2025.02"

  - import_adapter: fewswebservice
    source_id: simulated_IFS
    data_type: simulated_forecast_ensemble
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.sim
    module_instance_id: ElbowRavenIFSForecast
    ensemble_id: IFS
    webservice_version: "2025.02"
scores:
  - score_adapter: crps_for_ensemble
  - score_adapter: rank_histogram
    reduce_dims:
      - forecast_reference_time
id_mapping: 
  variable:
    discharge:
      observed: QR.obs
      simulated_GEFS: QR.sim
      simulated_GEPS: QR.sim
      simulated_IFS: QR.sim
