"""Pydantic schema definition for a fews compatible netcdf file.

To generate a yaml / json file with the json representation of this schema:
    with FILEPATH.open() as myfile:
        yaml.dump(FewsNetcdfSchema.model_json_schema(), myfile)

To generate a pydantic schema from a yaml/json file, see datamodel_code_generator,
for example from https://docs.pydantic.dev/latest/integrations/datamodel_code_generator/
Note that this might generate a pydantic model that is not up-to-date with the latest
pydantic / python, and might need some modifications.

"""
# generated by datamodel-codegen:

# ruff: noqa: D101 Do not require class docstrings for the classes in this file

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class FileAttrs(BaseModel):
    Conventions: Literal["CF-1.6"]


# Is a stations dim required? Do we want to require a stations, or some other location dimension?
# Is analysis time required, or optional?
class SimDims(BaseModel):
    time: int
    analysis_time: int


class ObsDims(BaseModel):
    time: int


class TimeAttrs(BaseModel):
    # The other schema said this should be name, but the nc example file has standard_name. Which
    #  is correct?
    standard_name: Literal["time"]
    long_name: Literal["time"]


class CoordAttrs(BaseModel):
    # The other schema said this should be name, but the nc example file has standard_name. Which
    #  is correct?
    standard_name: str
    long_name: str


class TimeCoord(BaseModel):
    attrs: TimeAttrs | None = None


class Coord(BaseModel):
    attrs: CoordAttrs | None = None


# probably also want specific attrs for lat and lon coords, to have e.g. a units
# and, generally, is an axis attrs required for all coords?


class SimCoords(BaseModel):
    time: TimeCoord
    analysis_time: Coord
    lat: Coord
    lon: Coord


class ObsCoords(BaseModel):
    time: TimeCoord
    lat: Coord
    lon: Coord


class DataVarAttrs(BaseModel):
    long_name: str


class DataVars(BaseModel):
    attrs: DataVarAttrs


class FewsNetcdfFileInputSimSchema(BaseModel):
    attrs: FileAttrs
    dims: SimDims
    coords: SimCoords
    data_vars: dict[Annotated[str, Field(pattern=r"[a-zA-Z].*")], DataVars]


class FewsNetcdfFileInputObsSchema(BaseModel):
    attrs: FileAttrs
    dims: ObsDims
    coords: ObsCoords
    data_vars: dict[Annotated[str, Field(pattern=r"[a-zA-Z].*")], DataVars]
