name: DPyVerification CI
# Note that this workflow is referenced by name in other workflows,
#   any name change thus needs to be propagated.

on:
  push:
    branches:
    - main
  pull_request:
jobs:
# Run the linter (ruff and mypy)
  lint:
    name: Lint (ruff + mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --dev
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --check .
      - name: Mypy
        run: uv run mypy 
  # Run pytest on a matrix of Python versions and operating systems
  pytest:
    # Needs the linter to succeed, before test matrix will run
    needs: lint
    name: Pytest with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      # Cache uv to speed up CI workflow when lock file has not changed
      - name: Cache uv
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
      - name: Install uv
        run: pip install uv
      - name: Install project dependencies
        run: uv sync --dev
      - name: Run pytest
        run: |
          uv run pytest --junit-xml=test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml --cov=dpyverification --cov-report=term --cov-report=xml
      - uses: actions/upload-artifact@v7
        # Upload the test results, to be parsed by second workflow
        # Two workflows, in order to support PRs from forks, as per
        # explanation at https://github.com/dorny/test-reporter
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: test-results*.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: false
  