name: DPyVerification Test Report

on:
  workflow_run:
    workflows: ['DPyVerification CI'] # runs after CI workflow
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      # Separate workflow to parse the test results
      # Two workflows, in order to support PRs from forks, as per
      # explanation at https://github.com/dorny/test-reporter
      with:
        artifact: /test-results-(.*)/     # artifact name
        name: Test report $1              # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
